blank_issues_enabled: false
contact_links:
  - name: Question or discussion
    url: https://github.com/SuchanMadhikarmi/kubernetes-zero-to-production/discussions
    about: Ask questions and discuss the repository.
